name: deployment

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: [aws-ec2]

    steps:
    - uses: actions/checkout@v3
    - name: Pull Docker Image
      run: sudo docker pull sfazim/provider-management:latest
    - name: Delete Old Docker Image
      run: sudo docker rm -f provider-management-container || true
    - name: Create .env file
      run: |
        touch .env
        echo DATABASE_USER=${{ secrets.DATABASE_USER }} >> .env
        echo DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} >> .env
        echo DATABASE_HOST=${{ secrets.DATABASE_HOST }} >> .env
        echo DATABASE_PORT=${{ secrets.DATABASE_PORT }} >> .env
        echo DATABASE_NAME=${{ secrets.DATABASE_NAME }} >> .env
    - name: Run Docker-Compose
      run: sudo docker compose -f docker-compose.prod.yml up -d

